/*
==========================================================================================================================================================

-	Autor: Isaac Abdiel Sánchez López.
-	Fecha de creación: 06/11/2025.
-	Fecha de la última actualización: 07/11/2025.
-	Título: Datos de catálogo.
-	Descripción: En este archivo se insertan los datos de la tabla catálogo "procedimientos".

==========================================================================================================================================================
*/


GO
EXEC r4l.sp_insert_procedimiento 'Consulta médica general', 'Evaluación clínica básica del paciente, revisión de síntomas y elaboración de plan de tratamiento.';
EXEC r4l.sp_insert_procedimiento 'Consulta de seguimiento', 'Revisión de la evolución del paciente y ajuste del tratamiento previamente indicado.';
EXEC r4l.sp_insert_procedimiento 'Toma de signos vitales', 'Medición de presión arterial, frecuencia cardiaca, respiratoria y temperatura.';
EXEC r4l.sp_insert_procedimiento 'Curación simple de heridas', 'Limpieza, desinfección y colocación de apósito en heridas superficiales.';
EXEC r4l.sp_insert_procedimiento 'Curación avanzada de heridas', 'Manejo especializado de heridas profundas o con riesgo de infección.';
EXEC r4l.sp_insert_procedimiento 'Retiro de puntos de sutura', 'Extracción segura de suturas colocadas tras un procedimiento quirúrgico o cierre de herida.';
EXEC r4l.sp_insert_procedimiento 'Sutura simple', 'Cierre de heridas pequeñas con técnica básica de sutura.';
EXEC r4l.sp_insert_procedimiento 'Sutura compleja', 'Reparación de heridas profundas o extensas con técnica avanzada.';
EXEC r4l.sp_insert_procedimiento 'Yeso corto', 'Inmovilización parcial de una extremidad mediante yeso corto.';
EXEC r4l.sp_insert_procedimiento 'Colocación de férula', 'Aplicación de una férula para inmovilizar lesiones musculoesqueléticas.';
EXEC r4l.sp_insert_procedimiento 'Toma de muestra sanguínea', 'Obtención de sangre venosa para estudios de laboratorio.';
EXEC r4l.sp_insert_procedimiento 'Toma de glucosa capilar', 'Medición rápida de glucosa mediante punción en yema del dedo.';
EXEC r4l.sp_insert_procedimiento 'Electrocardiograma (ECG)', 'Registro gráfico de la actividad eléctrica del corazón en reposo.';
EXEC r4l.sp_insert_procedimiento 'Ultrasonido abdominal', 'Estudio de imágenes por ultrasonido de los órganos abdominales.';
EXEC r4l.sp_insert_procedimiento 'Ultrasonido pélvico', 'Evaluación por ultrasonido de órganos pélvicos.';
EXEC r4l.sp_insert_procedimiento 'Radiografía de tórax', 'Imagen radiológica para evaluar pulmones, corazón y estructuras torácicas.';
EXEC r4l.sp_insert_procedimiento 'Radiografía de extremidad', 'Estudio por rayos X para detección de fracturas o lesiones óseas.';
EXEC r4l.sp_insert_procedimiento 'Tomografía axial computarizada (TAC) simple', 'Estudio tomográfico sin contraste para evaluación estructural.';
EXEC r4l.sp_insert_procedimiento 'TAC con contraste', 'Tomografía con administración de medio de contraste para mejor visualización.';
EXEC r4l.sp_insert_procedimiento 'Resonancia magnética (RM) simple', 'Estudio de resonancia sin uso de contraste.';
EXEC r4l.sp_insert_procedimiento 'RM con contraste', 'Estudio de resonancia con medio de contraste para evaluación detallada.';
EXEC r4l.sp_insert_procedimiento 'Prueba de esfuerzo', 'Valoración del funcionamiento cardiaco durante actividad física controlada.';
EXEC r4l.sp_insert_procedimiento 'Nebulización', 'Administración de medicamentos inhalados mediante un nebulizador.';
EXEC r4l.sp_insert_procedimiento 'Intubación orotraqueal', 'Colocación de un tubo en la tráquea para asegurar vía aérea.';
EXEC r4l.sp_insert_procedimiento 'RCP avanzada', 'Maniobras y soporte avanzado para restablecer circulación y respiración.';
EXEC r4l.sp_insert_procedimiento 'Canalización periférica', 'Colocación de una vía intravenosa periférica.';
EXEC r4l.sp_insert_procedimiento 'Catéter venoso central', 'Inserción de un catéter en una vena central para medicamentos o monitoreo.';
EXEC r4l.sp_insert_procedimiento 'Sondaje vesical', 'Colocación de sonda urinaria para drenaje o monitoreo.';
EXEC r4l.sp_insert_procedimiento 'Lavado gástrico', 'Procedimiento para vaciar el contenido gástrico en casos específicos.';
EXEC r4l.sp_insert_procedimiento 'Lavado ótico', 'Eliminación de cerumen mediante irrigación controlada.';
EXEC r4l.sp_insert_procedimiento 'Aplicación de inyección intramuscular', 'Administración de medicamento en tejido muscular.';
EXEC r4l.sp_insert_procedimiento 'Aplicación de inyección subcutánea', 'Administración de medicamento en tejido subcutáneo.';
EXEC r4l.sp_insert_procedimiento 'Aplicación de inyección intravenosa', 'Admininistración directa del medicamento en vena.';
EXEC r4l.sp_insert_procedimiento 'Biopsia por aspiración con aguja fina de tiroides', 'Obtención de tejido tiroideo para estudio citológico.';
EXEC r4l.sp_insert_procedimiento 'Biopsia de piel', 'Recolección de muestra de piel para diagnóstico histopatológico.';
EXEC r4l.sp_insert_procedimiento 'Biopsia de mama', 'Extracción de tejido mamario para estudio histológico.';
EXEC r4l.sp_insert_procedimiento 'Lavado articular', 'Irrigación de una articulación para extracción de residuos o sustancias.';
EXEC r4l.sp_insert_procedimiento 'Punción lumbar', 'Obtención de líquido cefalorraquídeo para análisis.';
EXEC r4l.sp_insert_procedimiento 'Paracentesis', 'Extracción de líquido ascítico de la cavidad abdominal.';
EXEC r4l.sp_insert_procedimiento 'Toracocentesis', 'Extracción de líquido pleural para estudio o alivio.';
EXEC r4l.sp_insert_procedimiento 'Electroencefalograma (EEG)', 'Registro de la actividad eléctrica cerebral para diagnóstico neurológico.';
EXEC r4l.sp_insert_procedimiento 'Espirometría', 'Prueba de función pulmonar para medir volúmenes y flujos respiratorios.';
EXEC r4l.sp_insert_procedimiento 'Endoscopia digestiva alta', 'Visualización del esófago, estómago y duodeno con endoscopio.';
EXEC r4l.sp_insert_procedimiento 'Colonoscopia', 'Exploración del colon mediante endoscopio flexible.';
EXEC r4l.sp_insert_procedimiento 'Rectosigmoidoscopia', 'Evaluación del recto y sigma con endoscopio.';
EXEC r4l.sp_insert_procedimiento 'Lavado peritoneal diagnóstico', 'Procedimiento para detectar sangrado o perforación abdominal.';
EXEC r4l.sp_insert_procedimiento 'Ecocardiograma transtorácico','Estudio por ultrasonido para evaluar estructura y función cardiaca.';
EXEC r4l.sp_insert_procedimiento 'Ecocardiograma transesofágico', 'Estudio cardíaco avanzado mediante sonda introducida al esófago.';
EXEC r4l.sp_insert_procedimiento 'Holter 24 horas', 'Monitoreo electrocardiográfico continuo durante 24 horas.';
EXEC r4l.sp_insert_procedimiento 'MAPA (Monitoreo ambulatorio de presión arterial)', 'Registro continuo de presión arterial durante 24 horas.';
EXEC r4l.sp_insert_procedimiento 'Artrocentesis', 'Punción de una articulación para extraer líquido sinovial con fines diagnósticos o terapéuticos.';
EXEC r4l.sp_insert_procedimiento 'Biopsia por aguja gruesa', 'Obtención de tejido mediante aguja para diagnóstico histopatológico.';
EXEC r4l.sp_insert_procedimiento 'Toracocentesis', 'Drenaje de líquido pleural mediante punción en la cavidad torácica.';
EXEC r4l.sp_insert_procedimiento 'Paracentesis diagnóstica', 'Extracción de líquido peritoneal para análisis en pacientes con ascitis.';
EXEC r4l.sp_insert_procedimiento 'Pericardiocentesis', 'Punción del pericardio para extraer líquido y aliviar taponamiento cardiaco.';
EXEC r4l.sp_insert_procedimiento 'Intubación orotraqueal', 'Inserción de un tubo en la tráquea para asegurar la vía aérea.';
EXEC r4l.sp_insert_procedimiento 'Ventilación mecánica invasiva', 'Soporte respiratorio mediante ventilador conectado a tubo endotraqueal.';
EXEC r4l.sp_insert_procedimiento 'Ventilación no invasiva', 'Soporte respiratorio con mascarilla sin necesidad de intubación.';
EXEC r4l.sp_insert_procedimiento 'Sedación consciente', 'Administración de fármacos para inducir sedación ligera durante procedimientos.';
EXEC r4l.sp_insert_procedimiento 'Sedación profunda', 'Inducción de un estado de sedación en el que el paciente no responde a estímulos.';
EXEC r4l.sp_insert_procedimiento 'Anestesia general', 'Inducción de inconsciencia y pérdida total de sensibilidad durante cirugía.';
EXEC r4l.sp_insert_procedimiento 'Anestesia regional', 'Bloqueo de sensibilidad en una región del cuerpo mediante inyección anestésica.';
EXEC r4l.sp_insert_procedimiento 'Bloqueo nervioso periférico', 'Inyección de anestésico cerca de un nervio para analgesia de extremidades.';
EXEC r4l.sp_insert_procedimiento 'Colocación de férula', 'Inmovilización temporal de un miembro lesionado.';
EXEC r4l.sp_insert_procedimiento 'Reducción cerrada de fractura', 'Alineación manual de huesos fracturados sin cirugía abierta.';
EXEC r4l.sp_insert_procedimiento 'Yeso ortopédico', 'Aplicación de yeso para inmovilizar extremidades en fracturas o lesiones.';
EXEC r4l.sp_insert_procedimiento 'Escayola de fibra de vidrio', 'Inmovilización ligera y resistente en fracturas.';
EXEC r4l.sp_insert_procedimiento 'Curación de heridas complejas', 'Limpieza, desbridamiento y vendaje de heridas profundas o infectadas.';
EXEC r4l.sp_insert_procedimiento 'Suturas cutáneas', 'Cierre de heridas mediante puntadas con hilo quirúrgico.';
EXEC r4l.sp_insert_procedimiento 'Retiro de puntos de sutura', 'Extracción de suturas tras cicatrización adecuada.';
EXEC r4l.sp_insert_procedimiento 'Drenaje de absceso', 'Incisión y vaciamiento del contenido purulento de un absceso.';
EXEC r4l.sp_insert_procedimiento 'Colocación de dren Penrose', 'Inserción de dren pasivo para evacuación de fluidos.';
EXEC r4l.sp_insert_procedimiento 'Colocación de dren Jackson-Pratt', 'Instalación de dren cerrado con sistema de succión.';
EXEC r4l.sp_insert_procedimiento 'Cauterización química', 'Aplicación de sustancias para detener sangrado o eliminar tejido.';
EXEC r4l.sp_insert_procedimiento 'Cauterización eléctrica', 'Uso de electrocauterio para cortar o coagular tejidos.';
EXEC r4l.sp_insert_procedimiento 'Extracción de cuerpo extraño cutáneo', 'Retiro de objetos incrustados en piel o tejido superficial.';
EXEC r4l.sp_insert_procedimiento 'Lavado gástrico', 'Instilación y extracción de líquido por sonda para descontaminación gástrica.';
EXEC r4l.sp_insert_procedimiento 'Colocación de sonda Foley', 'Inserción de sonda urinaria para drenaje de vejiga.';
EXEC r4l.sp_insert_procedimiento 'Retiro de sonda vesical', 'Extracción de catéter urinario después del tratamiento.';
EXEC r4l.sp_insert_procedimiento 'Cistoscopia diagnóstica', 'Visualización interna de vejiga mediante endoscopio.';
EXEC r4l.sp_insert_procedimiento 'Electroencefalograma (EEG)', 'Registro de actividad eléctrica cerebral.';
EXEC r4l.sp_insert_procedimiento 'Holter de 24 horas', 'Monitoreo ambulatorio continuo del ritmo cardiaco.';
EXEC r4l.sp_insert_procedimiento 'Prueba de esfuerzo', 'Evaluación del funcionamiento cardiaco bajo ejercicio controlado.';
EXEC r4l.sp_insert_procedimiento 'Curva de tolerancia a la glucosa', 'Medición seriada de glucosa tras carga oral controlada.';
EXEC r4l.sp_insert_procedimiento 'Dilatación esofágica', 'Apertura del esófago estrechado mediante dilatadores.';
EXEC r4l.sp_insert_procedimiento 'Colonoscopia diagnóstica', 'Exploración endoscópica del colon para diagnóstico.';
EXEC r4l.sp_insert_procedimiento 'Rectosigmoidoscopia', 'Evaluación del recto y colon sigmoid mediante endoscopio.';
EXEC r4l.sp_insert_procedimiento 'Extracción de pólipos', 'Resección endoscópica de pólipos en intestino o colon.';
EXEC r4l.sp_insert_procedimiento 'Biopsia endoscópica', 'Obtención de muestras de tejido mediante endoscopio.';
EXEC r4l.sp_insert_procedimiento 'Cistografía retrógrada', 'Estudio radiológico de vejiga mediante contraste.';
EXEC r4l.sp_insert_procedimiento 'Nefrostomía percutánea', 'Inserción de catéter para drenar el riñón obstruido.';
EXEC r4l.sp_insert_procedimiento 'Diálisis peritoneal', 'Depuración de sangre mediante intercambio de líquidos en cavidad abdominal.';
EXEC r4l.sp_insert_procedimiento 'Hemodiálisis', 'Filtrado extracorpóreo de sangre a través de un dializador.';
EXEC r4l.sp_insert_procedimiento 'Terapia de presión negativa', 'Uso de vacío para favorecer cicatrización de heridas.';
EXEC r4l.sp_insert_procedimiento 'Colocación de marcapasos temporal', 'Implantación transitoria de dispositivo para controlar ritmo cardíaco.';
EXEC r4l.sp_insert_procedimiento 'Cardioversión eléctrica', 'Aplicación de descarga controlada para restaurar ritmo cardíaco.';
EXEC r4l.sp_insert_procedimiento 'Desfibrilación', 'Choque eléctrico para revertir arritmias potencialmente mortales.';
EXEC r4l.sp_insert_procedimiento 'Taponamiento nasal anterior', 'Colocación de material para detener epistaxis leve a moderada.';
EXEC r4l.sp_insert_procedimiento 'Taponamiento nasal posterior', 'Control de hemorragia nasal mediante dispositivos nasales posteriores.';
EXEC r4l.sp_insert_procedimiento 'Nebulización terapéutica', 'Administración de medicamentos inhalados en forma de aerosol.';
EXEC r4l.sp_insert_procedimiento 'Broncoscopia diagnóstica', 'Evaluación de tráquea y bronquios mediante endoscopio flexible.';
EXEC r4l.sp_insert_procedimiento 'Broncoscopia terapéutica', 'Extracción de secreciones, cuerpos extraños o control de sangrado en vía aérea.';
EXEC r4l.sp_insert_procedimiento 'Lavado bronquioalveolar', 'Instilación y aspiración de solución en pulmones para análisis.';
EXEC r4l.sp_insert_procedimiento 'Biopsia transbronquial', 'Obtención de muestras pulmonares mediante broncoscopio.';
EXEC r4l.sp_insert_procedimiento 'Pleurodesis', 'Instilación de sustancias en la pleura para evitar derrames recurrentes.';
EXEC r4l.sp_insert_procedimiento 'Traqueostomía percutánea', 'Apertura de la tráquea para colocar cánula respiratoria.';
EXEC r4l.sp_insert_procedimiento 'Laringoscopia directa', 'Visualización de cuerdas vocales y vía aérea superior.';
EXEC r4l.sp_insert_procedimiento 'Test de función pulmonar', 'Medición de capacidad y flujo respiratorio.';
EXEC r4l.sp_insert_procedimiento 'Toracostomía con sello de agua', 'Colocación de tubo torácico para drenar aire o líquido.';
EXEC r4l.sp_insert_procedimiento 'Ultrasonido abdominal', 'Evaluación de órganos abdominales mediante ultrasonido.';
EXEC r4l.sp_insert_procedimiento 'Ultrasonido pélvico', 'Estudio ginecológico o urológico mediante ultrasonido.';
EXEC r4l.sp_insert_procedimiento 'Ultrasonido obstétrico', 'Evaluación de embarazo mediante ultrasonido.';
EXEC r4l.sp_insert_procedimiento 'Doppler vascular', 'Evaluación del flujo sanguíneo en arterias y venas.';
EXEC r4l.sp_insert_procedimiento 'Radiografía simple', 'Imágenes de estructura ósea y tejidos mediante rayos X.';
EXEC r4l.sp_insert_procedimiento 'Tomografía axial computarizada', 'Estudio de imágenes en cortes mediante rayos X y computadora.';
EXEC r4l.sp_insert_procedimiento 'Resonancia magnética', 'Obtención de imágenes mediante campos magnéticos y radiofrecuencia.';
EXEC r4l.sp_insert_procedimiento 'Angiografía', 'Visualización de vasos sanguíneos con medio de contraste.';
EXEC r4l.sp_insert_procedimiento 'Colocación de catéter venoso central', 'Inserción de catéter en vena subclavia, yugular o femoral.';
EXEC r4l.sp_insert_procedimiento 'Colocación de catéter arterial', 'Inserción de catéter en arteria para monitorización continua.';
EXEC r4l.sp_insert_procedimiento 'Punción lumbar', 'Obtención de líquido cefalorraquídeo para análisis.';
EXEC r4l.sp_insert_procedimiento 'Biopsia de médula ósea', 'Obtención de hueso y médula para estudios hematológicos.';
EXEC r4l.sp_insert_procedimiento 'Aspirado de médula ósea', 'Obtención de médula para análisis morfológico.';
EXEC r4l.sp_insert_procedimiento 'Transfusión sanguínea', 'Administración de sangre o hemoderivados.';
EXEC r4l.sp_insert_procedimiento 'Terapia transfusional masiva', 'Protocolo de transfusión rápida en hemorragias graves.';
EXEC r4l.sp_insert_procedimiento 'Colocación de reservorio subcutáneo', 'Implantación de dispositivo para acceso venoso prolongado.';
EXEC r4l.sp_insert_procedimiento 'Colposcopia', 'Visualización del cuello uterino para detectar lesiones.';
EXEC r4l.sp_insert_procedimiento 'Crioterapia ginecológica', 'Congelación de lesiones cervicales o vaginales.';
EXEC r4l.sp_insert_procedimiento 'Inserción de DIU', 'Colocación de dispositivo intrauterino anticonceptivo.';
EXEC r4l.sp_insert_procedimiento 'Retiro de DIU', 'Extracción de dispositivo intrauterino.';
EXEC r4l.sp_insert_procedimiento 'Amniocentesis', 'Extracción de líquido amniótico para estudios prenatales.';
EXEC r4l.sp_insert_procedimiento 'Version cefálica externa', 'Maniobra para alinear al feto en presentación cefálica.';
EXEC r4l.sp_insert_procedimiento 'Monitorización fetal no estresante', 'Evaluación del bienestar fetal mediante registros cardiacos.';
EXEC r4l.sp_insert_procedimiento 'Toma de Papanicolaou', 'Obtención de células cervicales para tamizaje.';
EXEC r4l.sp_insert_procedimiento 'Masaje uterino bimanual', 'Maniobra para controlar hemorragia postparto.';
EXEC r4l.sp_insert_procedimiento 'Sutura de desgarro perineal', 'Reparación de lesiones durante el parto.';
EXEC r4l.sp_insert_procedimiento 'Reanimación neonatal', 'Intervenciones para estabilizar recién nacidos en riesgo.';
EXEC r4l.sp_insert_procedimiento 'Circuncisión', 'Resección quirúrgica del prepucio del pene.';
EXEC r4l.sp_insert_procedimiento 'Orquidopexia', 'Fijación quirúrgica del testículo no descendido.';
EXEC r4l.sp_insert_procedimiento 'Vasectomía', 'Sección de conductos deferentes para esterilización masculina.';
EXEC r4l.sp_insert_procedimiento 'Biopsia testicular', 'Obtención de tejido testicular para estudios de fertilidad.';
EXEC r4l.sp_insert_procedimiento 'Prostatectomía transuretral', 'Resección de próstata mediante endoscopia.';
EXEC r4l.sp_insert_procedimiento 'Cistoscopia terapéutica', 'Procedimiento para extracción de cálculos o control de sangrado.';
EXEC r4l.sp_insert_procedimiento 'Litotricia extracorpórea', 'Fragmentación de cálculos renales mediante ondas de choque.';
EXEC r4l.sp_insert_procedimiento 'Cateterismo vesical suprapúbico', 'Inserción de catéter a través de la pared abdominal hacia la vejiga.';
EXEC r4l.sp_insert_procedimiento 'Electromiografía', 'Evaluación de actividad eléctrica de músculos.';
EXEC r4l.sp_insert_procedimiento 'Estudios de conducción nerviosa', 'Evaluación de velocidad y función de nervios periféricos.';
EXEC r4l.sp_insert_procedimiento 'Aplicación de toxina botulínica', 'Inyección para tratar espasticidad o trastornos neurológicos.';
EXEC r4l.sp_insert_procedimiento 'Bloqueo facetario', 'Inyección analgésica en articulaciones facetarias de columna.';
EXEC r4l.sp_insert_procedimiento 'Infiltración epidural', 'Administración de esteroides en espacio epidural para dolor lumbar.';
EXEC r4l.sp_insert_procedimiento 'Apendicectomía', 'Resección quirúrgica del apéndice por apendicitis aguda.';
EXEC r4l.sp_insert_procedimiento 'Colecistectomía laparoscópica', 'Extirpación de la vesícula biliar mediante técnica mínimamente invasiva.';
EXEC r4l.sp_insert_procedimiento 'Colecistectomía abierta', 'Resección de la vesícula mediante incisión abdominal.';
EXEC r4l.sp_insert_procedimiento 'Hernioplastia inguinal', 'Reparación quirúrgica de hernia inguinal con o sin malla.';
EXEC r4l.sp_insert_procedimiento 'Hernioplastia umbilical', 'Reparación de hernia umbilical con malla.';
EXEC r4l.sp_insert_procedimiento 'Hernioplastia ventral', 'Reparación de hernia de pared abdominal.';
EXEC r4l.sp_insert_procedimiento 'Hemicolectomía derecha', 'Resección del colon derecho con anastomosis primaria.';
EXEC r4l.sp_insert_procedimiento 'Hemicolectomía izquierda', 'Resección del colon izquierdo con anastomosis.';
EXEC r4l.sp_insert_procedimiento 'Colectomía total', 'Resección completa del colon.';
EXEC r4l.sp_insert_procedimiento 'Aspiración y drenaje de absceso abdominal', 'Evacuación quirúrgica de colección purulenta.';
EXEC r4l.sp_insert_procedimiento 'Laparotomía exploratoria', 'Apertura quirúrgica del abdomen para diagnóstico o tratamiento.';
EXEC r4l.sp_insert_procedimiento 'Sutura de perforación intestinal', 'Cierre de perforación en intestino delgado o grueso.';
EXEC r4l.sp_insert_procedimiento 'Gastrectomía parcial', 'Resección de parte del estómago por úlcera o tumor.';
EXEC r4l.sp_insert_procedimiento 'Gastrectomía total', 'Extirpación completa del estómago.';
EXEC r4l.sp_insert_procedimiento 'Funduplicatura de Nissen', 'Corrección quirúrgica del reflujo gastroesofágico.';
EXEC r4l.sp_insert_procedimiento 'Pancreatectomía distal', 'Resección de la porción distal del páncreas.';
EXEC r4l.sp_insert_procedimiento 'Reparación de perforación gástrica', 'Cierre de perforación del estómago.';
EXEC r4l.sp_insert_procedimiento 'Hemorragia digestiva: control quirúrgico', 'Ligadura o resección para controlar sangrado gastrointestinal.';
EXEC r4l.sp_insert_procedimiento 'Esplenectomía', 'Extirpación total o parcial del bazo.';
EXEC r4l.sp_insert_procedimiento 'Toracotomía', 'Apertura quirúrgica del tórax para acceso a órganos torácicos.';
EXEC r4l.sp_insert_procedimiento 'Toracoscopia', 'Procedimiento mínimamente invasivo para evaluar la cavidad torácica.';
EXEC r4l.sp_insert_procedimiento 'Pleurectomía', 'Resección parcial o total de la pleura.';
EXEC r4l.sp_insert_procedimiento 'Neumonectomía', 'Resección completa de un pulmón.';
EXEC r4l.sp_insert_procedimiento 'Lobectomía pulmonar', 'Resección de un lóbulo del pulmón.';
EXEC r4l.sp_insert_procedimiento 'Segmentectomía pulmonar', 'Extirpación de un segmento pulmonar.';
EXEC r4l.sp_insert_procedimiento 'Craneotomía por hematoma subdural', 'Apertura del cráneo para evacuar hematoma subdural.';
EXEC r4l.sp_insert_procedimiento 'Craneotomía por tumor cerebral', 'Resección quirúrgica de tumor intracraneal.';
EXEC r4l.sp_insert_procedimiento 'Descompresión medular', 'Liberación de presión sobre la médula espinal.';
EXEC r4l.sp_insert_procedimiento 'Fusión vertebral', 'Estabilización de segmentos vertebrales mediante implantes.';
EXEC r4l.sp_insert_procedimiento 'Laminectomía', 'Resección de lámina vertebral para descompresión.';
EXEC r4l.sp_insert_procedimiento 'Artroplastia total de cadera', 'Reemplazo completo de articulación coxofemoral.';
EXEC r4l.sp_insert_procedimiento 'Artroplastia total de rodilla', 'Reemplazo total de la articulación de la rodilla.';
EXEC r4l.sp_insert_procedimiento 'Reducción abierta y fijación interna de fractura', 'Estabilización de fracturas mediante placas o tornillos.';
EXEC r4l.sp_insert_procedimiento 'Artroscopia de rodilla', 'Procedimiento mínimamente invasivo para diagnóstico y reparación articular.';
EXEC r4l.sp_insert_procedimiento 'Reparación del manguito rotador', 'Corrección de desgarros en hombro.';
EXEC r4l.sp_insert_procedimiento 'Tratamiento quirúrgico de fractura de cadera', 'Osteosíntesis o artroplastia según el caso.';
EXEC r4l.sp_insert_procedimiento 'Orquiectomía', 'Extirpación quirúrgica de uno o ambos testículos.';
EXEC r4l.sp_insert_procedimiento 'Prostatectomía radical', 'Resección completa de la próstata por cáncer.';
EXEC r4l.sp_insert_procedimiento 'Nefrectomía parcial', 'Resección de parte del riñón.';
EXEC r4l.sp_insert_procedimiento 'Nefrectomía radical', 'Extirpación completa del riñón.';
EXEC r4l.sp_insert_procedimiento 'Cistolitotomía', 'Extracción quirúrgica de cálculos vesicales.';
EXEC r4l.sp_insert_procedimiento 'Histerectomía total', 'Extirpación completa del útero.';
EXEC r4l.sp_insert_procedimiento 'Histerectomía subtotal', 'Resección del cuerpo uterino preservando el cuello.';
EXEC r4l.sp_insert_procedimiento 'Salpingectomía', 'Resección de una o ambas trompas de Falopio.';
EXEC r4l.sp_insert_procedimiento 'Ooforectomía', 'Extirpación de uno o ambos ovarios.';
EXEC r4l.sp_insert_procedimiento 'Cesárea', 'Extracción del feto mediante incisión abdominal y uterina.';
EXEC r4l.sp_insert_procedimiento 'Cirugía de endometriosis', 'Resección de lesiones endometriósicas.';
EXEC r4l.sp_insert_procedimiento 'Adenoidectomía', 'Extirpación de tejido adenoideo.';
EXEC r4l.sp_insert_procedimiento 'Amigdalectomía', 'Resección de amígdalas palatinas.';
EXEC r4l.sp_insert_procedimiento 'Extracción de cuerpo extraño', 'Remoción quirúrgica de un objeto alojado en tejidos blandos, cavidades o estructuras corporales.';
EXEC r4l.sp_insert_procedimiento 'Drenaje de absceso profundo', 'Procedimiento quirúrgico para drenar colecciones purulentas localizadas en tejidos profundos.';
EXEC r4l.sp_insert_procedimiento 'Cauterización quirúrgica', 'Uso de calor o electricidad para destruir tejido o controlar sangrado durante una intervención.';
EXEC r4l.sp_insert_procedimiento 'Reducción quirúrgica de hernia', 'Corrección quirúrgica de una hernia mediante reposición del contenido herniado y reparación del defecto.';
EXEC r4l.sp_insert_procedimiento 'Cirugía de quiste sebáceo complicado', 'Extirpación de quistes sebáceos infectados, rotos o de gran tamaño.';
EXEC r4l.sp_insert_procedimiento 'Desbridamiento quirúrgico extenso', 'Remoción profunda de tejido necrótico o infectado en heridas graves.';
EXEC r4l.sp_insert_procedimiento 'Extirpación de tumor cutáneo', 'Resección de masas o tumores localizados en piel o tejido subcutáneo.';
EXEC r4l.sp_insert_procedimiento 'Liberación quirúrgica de adherencias', 'Separación de bandas fibrosas que restringen movimiento o función de órganos.';
EXEC r4l.sp_insert_procedimiento 'Reparación de tendón', 'Corrección quirúrgica de tendones seccionados o dañados.';
EXEC r4l.sp_insert_procedimiento 'Reparación de nervio periférico', 'Sutura o reconstrucción microquirúrgica de nervios lesionados.';
EXEC r4l.sp_insert_procedimiento 'Fasciotomía', 'Incisión quirúrgica de la fascia para aliviar presión en un compartimiento muscular.';
EXEC r4l.sp_insert_procedimiento 'Sinovectomía', 'Resección parcial o total del tejido sinovial inflamado de una articulación.';
EXEC r4l.sp_insert_procedimiento 'Artrodesis menor', 'Fusión quirúrgica de pequeñas articulaciones para eliminar dolor o inestabilidad.';
EXEC r4l.sp_insert_procedimiento 'Colocación de drenaje quirúrgico', 'Inserción de un dispositivo para permitir la salida de fluidos después de una cirugía.';
EXEC r4l.sp_insert_procedimiento 'Biopsia quirúrgica profunda', 'Obtención de tejido mediante incisión para análisis histopatológico.';
EXEC r4l.sp_insert_procedimiento 'Reparación de lesión vascular menor', 'Corrección quirúrgica de vasos sanguíneos pequeños o medianos.';
EXEC r4l.sp_insert_procedimiento 'Escisión de lipoma grande', 'Resección quirúrgica de lipomas de gran tamaño o localización complicada.';
EXEC r4l.sp_insert_procedimiento 'Cirugía de bursa inflamada', 'Resección o drenaje de bolsas sinoviales inflamadas o infectadas.';
EXEC r4l.sp_insert_procedimiento 'Corrección quirúrgica de dedo en gatillo', 'Liberación del tendón flexor atrapado para restaurar el movimiento del dedo.';
EXEC r4l.sp_insert_procedimiento 'Resección de ganglión complejo', 'Extirpación quirúrgica de gangliones de muñeca o manos con características recurrentes o profundas.';
EXEC r4l.sp_insert_procedimiento 'Colecistectomía laparoscópica', 'Remoción de la vesícula biliar utilizando técnica laparoscópica para tratar litiasis o inflamación.';
EXEC r4l.sp_insert_procedimiento 'Apendicectomía laparoscópica', 'Extirpación del apéndice inflamado mediante abordaje mínimamente invasivo.';
EXEC r4l.sp_insert_procedimiento 'Hernioplastia inguinal', 'Reparación quirúrgica de hernia inguinal con colocación de malla.';
EXEC r4l.sp_insert_procedimiento 'Resección de tumor benigno', 'Extirpación quirúrgica de tumores benignos localizados en tejidos blandos u órganos superficiales.';
EXEC r4l.sp_insert_procedimiento 'Cirugía de varices', 'Procedimiento quirúrgico para remover o cerrar venas varicosas en extremidades.';
EXEC r4l.sp_insert_procedimiento 'Hemorroidecomía', 'Extirpación quirúrgica de hemorroides internas o externas.';
EXEC r4l.sp_insert_procedimiento 'Fistulectomía anal', 'Resección completa de una fístula anal para eliminar infección y prevenir recurrencias.';
EXEC r4l.sp_insert_procedimiento 'Mastectomía parcial', 'Remoción quirúrgica de una porción de tejido mamario afectado por tumores o lesiones.';
EXEC r4l.sp_insert_procedimiento 'Tiroidectomía parcial', 'Resección de uno de los lóbulos de la glándula tiroides o del istmo.';
EXEC r4l.sp_insert_procedimiento 'Cirugía de hidrocele', 'Reparación quirúrgica de acumulación de líquido alrededor del testículo.';
EXEC r4l.sp_insert_procedimiento 'Orquidopexia', 'Fijación quirúrgica del testículo en el escroto para tratar criptorquidia o torsión.';
EXEC r4l.sp_insert_procedimiento 'Histerectomía', 'Remoción quirúrgica del útero por patologías como miomas, sangrado severo o cáncer.';
EXEC r4l.sp_insert_procedimiento 'Salpingectomía', 'Extirpación de una o ambas trompas de Falopio por infección, embarazo ectópico o tumores.';
EXEC r4l.sp_insert_procedimiento 'Ooforectomía', 'Extirpación de uno o ambos ovarios debido a quistes, tumores o torsión.';
EXEC r4l.sp_insert_procedimiento 'Cirugía de quiste ovárico', 'Resección de quistes ováricos preservando, cuando es posible, la función del ovario.';
EXEC r4l.sp_insert_procedimiento 'Cistoscopía quirúrgica', 'Procedimiento endoscópico para visualizar y tratar lesiones dentro de la vejiga.';
EXEC r4l.sp_insert_procedimiento 'Ureteroscopía con extracción de cálculos', 'Endoscopía del uréter para extraer piedras alojadas en la vía urinaria.';
EXEC r4l.sp_insert_procedimiento 'Cirugía de lipoma intramuscular', 'Extirpación quirúrgica de lipomas localizados dentro del tejido muscular.';
EXEC r4l.sp_insert_procedimiento 'Resección de ganglio linfático', 'Extracción de ganglios linfáticos para diagnóstico o tratamiento de infección o cáncer.';
EXEC r4l.sp_insert_procedimiento 'Cirugía de glándula salival', 'Resección parcial o total de glándulas salivales afectadas por tumores, cálculos o infecciones.';
EXEC r4l.sp_insert_procedimiento 'Amputación de extremidad', 'Remoción parcial o total de una extremidad debido a infecciones graves, trauma o enfermedades vasculares.';
EXEC r4l.sp_insert_procedimiento 'Desbridamiento quirúrgico extenso', 'Eliminación de tejido necrótico o infectado para favorecer la cicatrización.';
EXEC r4l.sp_insert_procedimiento 'Artroplastia total de rodilla', 'Reemplazo completo de la articulación de la rodilla con prótesis artificial.';
EXEC r4l.sp_insert_procedimiento 'Artroplastia total de cadera', 'Sustitución de la articulación de la cadera por una prótesis debido a degeneración o fractura.';
EXEC r4l.sp_insert_procedimiento 'Reparación de ligamento cruzado anterior', 'Reconstrucción del LCA mediante técnica artroscópica o abierta.';
EXEC r4l.sp_insert_procedimiento 'Reducción abierta y fijación interna de fractura', 'Alineación quirúrgica de una fractura con colocación de placas, tornillos o clavos.';
EXEC r4l.sp_insert_procedimiento 'Artroscopia de hombro', 'Procedimiento mínimamente invasivo para reparar lesiones en la articulación del hombro.';
EXEC r4l.sp_insert_procedimiento 'Cirugía de túnel carpiano', 'Liberación quirúrgica del nervio mediano para tratar síndrome del túnel carpiano.';
EXEC r4l.sp_insert_procedimiento 'Fusión espinal lumbar', 'Unión quirúrgica de dos o más vértebras lumbares para estabilizar la columna.';
EXEC r4l.sp_insert_procedimiento 'Laminectomía', 'Remoción de una porción del arco vertebral para aliviar compresión nerviosa.';
EXEC r4l.sp_insert_procedimiento 'Craneotomía para evacuación de hematoma', 'Apertura del cráneo para remover hematomas epidurales, subdurales o intracerebrales.';
EXEC r4l.sp_insert_procedimiento 'Microdiscectomía lumbar', 'Extracción de material discal que comprime nervios espinales mediante técnica microscópica.';
EXEC r4l.sp_insert_procedimiento 'Cirugía de epilepsia', 'Resección o modificación de zonas cerebrales que generan actividad epiléptica.';
EXEC r4l.sp_insert_procedimiento 'Tiroidectomía total', 'Extirpación completa de la glándula tiroides por cáncer o enfermedad tiroidea severa.';
EXEC r4l.sp_insert_procedimiento 'Paratiroidectomía', 'Remoción de una o más glándulas paratiroides por hiperparatiroidismo.';
EXEC r4l.sp_insert_procedimiento 'Lobectomía pulmonar', 'Extirpación de un lóbulo del pulmón por tumores, infecciones o malformaciones.';
EXEC r4l.sp_insert_procedimiento 'Neumonectomía', 'Remoción completa de un pulmón debido a cáncer avanzado o daño irreversible.';
EXEC r4l.sp_insert_procedimiento 'Resección de divertículo de Meckel', 'Extracción quirúrgica del divertículo en el intestino delgado para evitar complicaciones.';
EXEC r4l.sp_insert_procedimiento 'Cirugía de prolapso rectal', 'Corrección quirúrgica del protrusión del recto hacia el exterior del cuerpo.';
EXEC r4l.sp_insert_procedimiento 'Gastrectomía total', 'Remoción completa del estómago generalmente por cáncer gástrico.';
EXEC r4l.sp_insert_procedimiento 'Colecistectomía abierta', 'Remoción de la vesícula biliar mediante cirugía abierta debido a cálculos o inflamación severa.';
EXEC r4l.sp_insert_procedimiento 'Pancreatectomía parcial', 'Resección de una porción del páncreas por tumores o pancreatitis crónica.';
EXEC r4l.sp_insert_procedimiento 'Hepatectomía parcial', 'Extirpación quirúrgica de un segmento del hígado por lesiones benignas o malignas.';
EXEC r4l.sp_insert_procedimiento 'Esplenectomía', 'Remoción del bazo por traumatismo, enfermedad hematológica o tumores.';
EXEC r4l.sp_insert_procedimiento 'Colectomía parcial', 'Resección de una parte del colon por cáncer, diverticulitis o enfermedad inflamatoria intestinal.';
EXEC r4l.sp_insert_procedimiento 'Colectomía total', 'Resección completa del colon generalmente por cáncer o enfermedad inflamatoria extensa.';
EXEC r4l.sp_insert_procedimiento 'Ileostomía', 'Creación quirúrgica de una abertura del íleon hacia la pared abdominal para derivar el tránsito intestinal.';
EXEC r4l.sp_insert_procedimiento 'Colostomía', 'Apertura quirúrgica del colon hacia el abdomen para derivar las heces temporal o permanentemente.';
EXEC r4l.sp_insert_procedimiento 'Reparación de perforación gástrica', 'Cierre quirúrgico de una perforación en el estómago causada por úlcera o trauma.';
EXEC r4l.sp_insert_procedimiento 'Hemorroidectomía con técnica abierta', 'Remoción quirúrgica de hemorroides mediante incisión abierta.';
EXEC r4l.sp_insert_procedimiento 'Cirugía de fistula perianal compleja', 'Resección y cierre de trayectos fistulosos complicados alrededor del ano.';
EXEC r4l.sp_insert_procedimiento 'Litotricia quirúrgica', 'Extracción quirúrgica de cálculos urinarios grandes o impactados no tratados con litotricia extracorpórea.';
EXEC r4l.sp_insert_procedimiento 'Nefrectomía parcial', 'Resección de parte del riñón afectado por tumor o lesión renal.';
EXEC r4l.sp_insert_procedimiento 'Nefrectomía total', 'Extirpación completa del riñón por cáncer, traumatismo o enfermedad crónica.';
EXEC r4l.sp_insert_procedimiento 'Prostatectomía radical', 'Remoción total de la próstata generalmente por cáncer de próstata.';
EXEC r4l.sp_insert_procedimiento 'Resección transuretral de próstata', 'Procedimiento endoscópico para tratar hiperplasia prostática benigna.';
EXEC r4l.sp_insert_procedimiento 'Orquiectomía', 'Extirpación quirúrgica de uno o ambos testículos por cáncer o traumatismo.';
EXEC r4l.sp_insert_procedimiento 'Vasectomía', 'Procedimiento quirúrgico de esterilización masculina mediante corte y ligadura de los conductos deferentes.';
EXEC r4l.sp_insert_procedimiento 'Histerectomía subtotal', 'Remoción del útero dejando el cuello uterino, indicada por enfermedades benignas.';
EXEC r4l.sp_insert_procedimiento 'Reparación de prolapso uterino', 'Cirugía para reposicionar y fijar el útero descendido en su posición anatómica correcta.';
EXEC r4l.sp_insert_procedimiento 'Histerectomía total', 'Remoción completa del útero y cuello uterino, generalmente indicada por cáncer o patologías graves.';
EXEC r4l.sp_insert_procedimiento 'Ooforectomía', 'Extirpación quirúrgica de uno o ambos ovarios por tumores, quistes o enfermedades graves.';
EXEC r4l.sp_insert_procedimiento 'Salpingectomía', 'Resección de una o ambas trompas de Falopio, por embarazo ectópico o patología tumoral.';
EXEC r4l.sp_insert_procedimiento 'Reparación de ruptura uterina', 'Cierre quirúrgico de desgarros en el útero tras trauma o parto complicado.';
EXEC r4l.sp_insert_procedimiento 'Cirugía de endometriosis profunda', 'Extirpación de tejido endometrial que invade órganos pélvicos o abdominales.';
EXEC r4l.sp_insert_procedimiento 'Cesárea programada', 'Extracción del feto mediante incisión abdominal y uterina en embarazos de riesgo o complicados.';
EXEC r4l.sp_insert_procedimiento 'Cesárea de emergencia', 'Intervención urgente para salvar la vida de la madre o del feto en situaciones críticas.';
EXEC r4l.sp_insert_procedimiento 'Ligadura de trompas', 'Procedimiento de esterilización femenina mediante cierre o resección de las trompas de Falopio.';
EXEC r4l.sp_insert_procedimiento 'Reparación de episiotomía compleja', 'Sutura quirúrgica de desgarros graves en el periné tras parto.';
EXEC r4l.sp_insert_procedimiento 'Mastectomía total', 'Extirpación completa de la mama por cáncer u otras patologías graves.';
EXEC r4l.sp_insert_procedimiento 'Mastectomía parcial', 'Remoción de un segmento de la mama afectado por tumores o lesiones precancerosas.';
EXEC r4l.sp_insert_procedimiento 'Reconstrucción mamaria', 'Procedimiento quirúrgico para restaurar la forma y volumen de la mama tras mastectomía.';
EXEC r4l.sp_insert_procedimiento 'Cirugía de melanoma cutáneo', 'Resección del melanoma y márgenes de tejido sano para tratamiento oncológico.';
EXEC r4l.sp_insert_procedimiento 'Exéresis de lipoma', 'Extirpación quirúrgica de tumores benignos de tejido adiposo subcutáneo.';
EXEC r4l.sp_insert_procedimiento 'Cirugía de quiste sebáceo', 'Remoción completa de quistes sebáceos inflamados o recurrentes.';
EXEC r4l.sp_insert_procedimiento 'Cirugía reconstructiva de quemaduras', 'Restauración de piel y tejidos dañados por quemaduras graves mediante injertos o colgajos.';
EXEC r4l.sp_insert_procedimiento 'Frenotomía', 'Incisión quirúrgica del frenillo lingual o labial para mejorar movilidad y función.';
EXEC r4l.sp_insert_procedimiento 'Corrección de labio leporino', 'Reconstrucción quirúrgica para reparar malformaciones congénitas del labio superior.';
EXEC r4l.sp_insert_procedimiento 'Corrección de paladar hendido', 'Cierre quirúrgico del paladar para restaurar función y estética.';
EXEC r4l.sp_insert_procedimiento 'Reparación de hernia inguinal', 'Reparación quirúrgica de protrusión de intestino o tejido a través de la pared abdominal en la región inguinal.';
EXEC r4l.sp_insert_procedimiento 'Reparación de hernia femoral', 'Cierre quirúrgico de la protrusión a través del canal femoral, más frecuente en mujeres.';
EXEC r4l.sp_insert_procedimiento 'Reparación de hernia umbilical', 'Cierre de hernia en el ombligo mediante sutura o malla, indicada por protrusión intestinal o tejido.';
EXEC r4l.sp_insert_procedimiento 'Reparación de hernia hiatal', 'Cirugía para corregir el desplazamiento del estómago hacia el tórax a través del hiato diafragmático.';
EXEC r4l.sp_insert_procedimiento 'Apendicectomía abierta', 'Extirpación quirúrgica del apéndice inflamado mediante incisión abdominal convencional.';
EXEC r4l.sp_insert_procedimiento 'Apendicectomía laparoscópica', 'Extirpación del apéndice usando técnicas mínimamente invasivas con pequeñas incisiones.';
EXEC r4l.sp_insert_procedimiento 'Colecistectomía laparoscópica', 'Extracción de la vesícula biliar usando cirugía mínimamente invasiva.';
EXEC r4l.sp_insert_procedimiento 'Reparación de perforación intestinal', 'Cierre quirúrgico de perforaciones en el intestino causadas por enfermedad, trauma o úlceras.';
EXEC r4l.sp_insert_procedimiento 'Resección intestinal con anastomosis', 'Remoción de un segmento intestinal y unión de los extremos sanos para restaurar el tránsito intestinal.';
EXEC r4l.sp_insert_procedimiento 'Cirugía de diverticulitis complicada', 'Resección del segmento afectado del colon debido a inflamación severa o perforación.';
EXEC r4l.sp_insert_procedimiento 'Gastrectomía parcial', 'Resección de una parte del estómago por cáncer, úlceras graves o tumores benignos.';
EXEC r4l.sp_insert_procedimiento 'Gastrectomía total', 'Extirpación completa del estómago, generalmente por cáncer gástrico avanzado.';
EXEC r4l.sp_insert_procedimiento 'Funduplicatura de Nissen', 'Procedimiento para tratar reflujo gastroesofágico mediante envoltura del fundus gástrico alrededor del esófago.';
EXEC r4l.sp_insert_procedimiento 'Esófago-gastroplastia', 'Reconstrucción quirúrgica del esófago y estómago por estenosis, tumores o trauma.';
EXEC r4l.sp_insert_procedimiento 'Cirugía de urgencia por perforación gástrica', 'Cierre inmediato de la perforación para prevenir peritonitis y complicaciones graves.';
EXEC r4l.sp_insert_procedimiento 'Resección de tumor pancreático', 'Extirpación quirúrgica de tumores en cabeza, cuerpo o cola del páncreas.';
EXEC r4l.sp_insert_procedimiento 'Colangiopancreatografía quirúrgica', 'Procedimiento para explorar y tratar los conductos biliares y pancreáticos durante cirugía.';
EXEC r4l.sp_insert_procedimiento 'Hernioplastia inguinal con malla', 'Reparación de hernia inguinal usando malla sintética para reforzar la pared abdominal.';
EXEC r4l.sp_insert_procedimiento 'Hernioplastia umbilical con malla', 'Cierre de hernia umbilical mediante sutura reforzada con malla sintética.';
EXEC r4l.sp_insert_procedimiento 'Reparación de hernia incisional', 'Cierre quirúrgico de hernias que aparecen en cicatrices de cirugías previas.';
EXEC r4l.sp_insert_procedimiento 'Desbridamiento quirúrgico de úlceras', 'Eliminación de tejido muerto o infectado de úlceras para favorecer la cicatrización.';
GO